<a href="https://colab.research.google.com/github/sabilarizki/Preprocessing-Data/blob/main/Tugas%20Data%20Mining%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset =pd.read_csv('Customers.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(str(x)+"\n")
print(y)

[[1 'Male' 19 ... 39 'Healthcare' 1]
 [2 'Male' 21 ... 81 'Engineer' 3]
 [3 'Female' 20 ... 6 'Engineer' 1]
 ...
 [1998 'Male' 87 ... 14 'Healthcare' 9]
 [1999 'Male' 77 ... 4 'Executive' 7]
 [2000 'Male' 90 ... 52 'Entertainment' 5]]

[4 3 1 ... 2 2 2]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer (missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 4:5])
x[:, 4:5] = imputer.transform(x[:, 4:5])

print(x)

[[1 'Male' 19 ... 39.0 'Healthcare' 1]
 [2 'Male' 21 ... 81.0 'Engineer' 3]
 [3 'Female' 20 ... 6.0 'Engineer' 1]
 ...
 [1998 'Male' 87 ... 14.0 'Healthcare' 9]
 [1999 'Male' 77 ... 4.0 'Executive' 7]
 [2000 'Male' 90 ... 52.0 'Entertainment' 5]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer (transformers=[ ('encoder' , OneHotEncoder(sparse_output=False), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(x))

print(X)

[[1.0 0.0 0.0 ... 39.0 'Healthcare' 1]
 [0.0 1.0 0.0 ... 81.0 'Engineer' 3]
 [0.0 0.0 1.0 ... 6.0 'Engineer' 1]
 ...
 [0.0 0.0 0.0 ... 14.0 'Healthcare' 9]
 [0.0 0.0 0.0 ... 4.0 'Executive' 7]
 [0.0 0.0 0.0 ... 52.0 'Entertainment' 5]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

[3 2 0 ... 1 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

print(X_train)

[[1.0 0.0 0.0 ... 39.0 'Healthcare' 1]
 [0.0 0.0 0.0 ... 42.0 'Homemaker' 8]
 [0.0 0.0 0.0 ... 11.0 'Lawyer' 1]
 ...
 [0.0 0.0 0.0 ... 79.0 nan 7]
 [0.0 0.0 0.0 ... 34.0 'Healthcare' 0]
 [0.0 0.0 0.0 ... 88.0 'Executive' 0]]


In [ ]:
print(X_test)

[[0.0 0.0 0.0 ... 45.0 'Doctor' 0]
 [0.0 0.0 0.0 ... 31.0 'Lawyer' 0]
 [0.0 0.0 0.0 ... 43.0 'Executive' 8]
 ...
 [0.0 0.0 0.0 ... 97.0 'Artist' 1]
 [0.0 0.0 0.0 ... 92.0 'Doctor' 6]
 [0.0 0.0 0.0 ... 70.0 'Executive' 5]]


In [ ]:
print(y_train)

[3 1 3 ... 4 3 0]


In [ ]:
print(y_test)

[5 2 3 3 4 2 1 0 2 3 1 4 0 6 2 4 2 2 3 2 3 1 0 3 6 0 4 2 4 1 1 1 2 0 2 6 2
 3 3 6 1 2 3 6 6 3 3 2 3 5 1 2 2 1 3 1 2 6 2 3 1 2 3 2 2 3 4 1 1 5 2 2 0 6
 3 3 6 6 4 6 0 2 2 6 3 4 2 3 0 4 0 3 0 4 0 6 5 3 1 1 2 4 1 0 0 5 0 4 6 4 3
 5 4 6 5 2 0 6 3 2 5 2 6 5 0 6 2 5 3 3 2 6 4 2 4 5 5 4 5 1 1 2 5 5 0 4 5 3
 4 0 0 0 4 1 4 5 2 6 4 1 4 6 0 1 3 0 4 3 1 4 1 0 5 2 3 4 1 2 4 4 1 6 6 2 3
 1 1 6 1 5 5 6 6 6 2 2 2 0 1 5 1 2 4 5 4 3 3 6 2 5 3 1 7 4 1 1 5 6 5 5 4 3
 0 1 1 4 2 3 2 2 0 4 4 3 4 2 6 2 5 3 2 5 4 2 2 1 4 2 5 5 2 3 6 2 5 1 2 3 2
 7 5 6 1 1 6 3 4 6 5 3 4 5 5 4 5 1 1 1 2 3 1 6 0 2 1 2 6 3 0 5 2 0 3 5 2 1
 5 6 1 4 2 6 2 1 3 5 4 2 3 4 1 0 3 4 4 3 4 5 3 2 0 1 2 6 0 3 0 2 0 4 1 5 2
 1 4 4 2 0 2 6 0 5 4 0 2 5 1 1 3 0 1 4 0 1 5 1 4 5 4 5 1 6 4 5 3 1 0 2 6 2
 3 0 3 3 3 3 2 1 0 3 1 2 5 6 0 6 0 0 4 4 2 5 6 2 6 0 3 1 4 6]


In [ ]:
from sklearn. preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:5] = sc.fit_transform(X_train[:,:5])
X_test[:,:5] = sc.transform(X_test[:,:5])

print(X_train)

[[39.987498046263994 -0.025007816164017545 -0.02500781616401762 ... 39.0
  'Healthcare' 1]
 [-0.02500781616401751 -0.025007816164017545 -0.02500781616401762 ...
  42.0 'Homemaker' 8]
 [-0.02500781616401751 -0.025007816164017545 -0.02500781616401762 ...
  11.0 'Lawyer' 1]
 ...
 [-0.02500781616401751 -0.025007816164017545 -0.02500781616401762 ...
  79.0 nan 7]
 [-0.02500781616401751 -0.025007816164017545 -0.02500781616401762 ...
  34.0 'Healthcare' 0]
 [-0.02500781616401751 -0.025007816164017545 -0.02500781616401762 ...
  88.0 'Executive' 0]]


In [ ]:
print(X_test)

[[-0.02500781616401751 -0.025007816164017545 -0.02500781616401762 ...
  45.0 'Doctor' 0]
 [-0.02500781616401751 -0.025007816164017545 -0.02500781616401762 ...
  31.0 'Lawyer' 0]
 [-0.02500781616401751 -0.025007816164017545 -0.02500781616401762 ...
  43.0 'Executive' 8]
 ...
 [-0.02500781616401751 -0.025007816164017545 -0.02500781616401762 ...
  97.0 'Artist' 1]
 [-0.02500781616401751 -0.025007816164017545 -0.02500781616401762 ...
  92.0 'Doctor' 6]
 [-0.02500781616401751 -0.025007816164017545 -0.02500781616401762 ...
  70.0 'Executive' 5]]
